import Foundation
import Testing

@testable import StenoCore

/// Regenerates every generated fixture and compares hashes with
/// `MANIFEST.sha256` and bytes with the committed files. With
/// `STENO_UPDATE_SNAPSHOTS=1` it rewrites both instead. On a mismatch the
/// regenerated bytes land beside the fixture as `<name>.actual`.
@Suite struct FixtureManifestTests {
  @Test func generatedFixturesMatchTheManifestAndTheCommittedFiles() throws {
    if ProcessInfo.processInfo.environment[Snapshot.updateEnvironmentKey] == "1" {
      let outputs = try FixtureGenerator.generate(into: Fixtures.root)
      try Data(FixtureGenerator.manifest(outputs).utf8)
        .write(to: Fixtures.url("MANIFEST.sha256"), options: .atomic)
      return
    }

    let directory = try Fixtures.temporaryDirectory()
    defer { try? FileManager.default.removeItem(at: directory) }
    let outputs = try FixtureGenerator.generate(into: directory)
    let manifest = try String(contentsOf: Fixtures.url("MANIFEST.sha256"), encoding: .utf8)
    #expect(FixtureGenerator.manifest(outputs) == manifest)
    #expect(FixtureGenerator.parseManifest(manifest) == outputs)

    for output in outputs {
      let regenerated = try Data(contentsOf: directory.appendingPathComponent(output.relativePath))
      let committed = try? Data(contentsOf: Fixtures.url(output.relativePath))
      if regenerated != committed {
        try? regenerated.write(
          to: Fixtures.url(output.relativePath).appendingPathExtension("actual"), options: .atomic)
      }
      #expect(regenerated == committed, "\(output.relativePath) differs from the committed fixture")
      #expect(ContentHash.sha256Hex(regenerated) == output.sha256)
    }
  }

  @Test func everyAudioFixtureIsShortAnd16kMono() throws {
    for output in FixtureGenerator.cases {
      let info = try WAVAudioDecoder.info(Fixtures.url(output.relativePath))
      #expect(info.sampleRate == 16_000, "\(output.relativePath)")
      #expect(info.channels == 1, "\(output.relativePath)")
      #expect(info.frameCount <= 10 * 16_000, "\(output.relativePath) is over ten seconds")
    }
  }

  @Test func generatorIsDeterministic() {
    let first = FixtureGenerator.noise(seconds: 0.01, seed: 42, amplitude: 0.5)
    let second = FixtureGenerator.noise(seconds: 0.01, seed: 42, amplitude: 0.5)
    #expect(first == second)
    #expect(first != FixtureGenerator.noise(seconds: 0.01, seed: 43, amplitude: 0.5))
    #expect(first.count == 160)
    var generator = SplitMix64(seed: 1)
    #expect(generator.next() == 0x910A_2DEC_8902_5CC1)

    let mic = FixtureGenerator.conversation(seconds: 6, lanes: [.mic])
    let system = FixtureGenerator.conversation(seconds: 6, lanes: [.system])
    let mixed = FixtureGenerator.conversation(seconds: 6, lanes: [.mic, .system])
    #expect(mic.count == 96_000)
    #expect(mic[100] != 0, "A speaks first on the mic lane")
    #expect(system[100] == 0, "A speaks first on the mic lane")
    #expect(mic[30_000] == 0, "B speaks second on the system lane")
    #expect(system[30_050] != 0, "B speaks second on the system lane")
    #expect(mixed[100] == mic[100])
    #expect(mixed[30_050] == system[30_050])
    #expect(FixtureGenerator.conversationTurns(seconds: 6).map(\.speaker) == ["A", "B", "A", "B"])
  }

  @Test func sha256MatchesKnownVectors() {
    #expect(
      ContentHash.sha256Hex(Data())
        == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")
    #expect(
      ContentHash.sha256Hex(Data("abc".utf8))
        == "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
    #expect(
      PortableSHA256.hash(Data("abc".utf8)) == ContentHash.sha256(Data("abc".utf8)))
    let long = Data(repeating: 0x61, count: 1000)
    #expect(
      ContentHash.sha256Hex(long)
        == "41edece42d63e8d9bf515a9ba6932e1c20cbc9f5a5d134645adb5db1b9737ea3")
  }
}
