#!/usr/bin/env bash
#
# Regenerates crates/steno-core/tests/fixtures/schema.swift.sql: the schema of
# a database the Swift CLI created, in the normalised form the Rust schema
# parity test compares against (crates/steno-core/tests/schema_parity.rs).
# macOS only, because the Swift package is.
#
# Usage: scripts/dump-swift-schema.sh [--steno <path to the steno binary>]
#        [--out <fixture path>]
#
# Without --steno the CLI is built with `swift build -c release`. The query
# below and `steno_core::store::schema_dump` must stay the same text; the
# parity test fails when they drift.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
steno_bin=""
out="$repo_root/crates/steno-core/tests/fixtures/schema.swift.sql"

while [[ $# -gt 0 ]]; do
	case "$1" in
		--steno) steno_bin="$2"; shift 2 ;;
		--out) out="$2"; shift 2 ;;
		*) echo "unknown argument: $1" >&2; exit 2 ;;
	esac
done

if ! command -v sqlite3 >/dev/null; then
	echo "sqlite3 is required" >&2
	exit 1
fi

if [[ -z "$steno_bin" ]]; then
	(cd "$repo_root" && swift build -c release --product steno >&2)
	steno_bin="$(cd "$repo_root" && swift build -c release --show-bin-path)/steno"
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

"$steno_bin" dev db migrate --db "$tmp/steno.sqlite" >&2

# One line per sqlite_master row (auto-indexes included, their sql empty),
# then the applied GRDB migration identifiers in application order.
query="SELECT type || '|' || name || '|' || tbl_name || '|' || coalesce(sql, '') FROM sqlite_master ORDER BY type, name;
SELECT 'migration|' || identifier FROM grdb_migrations ORDER BY rowid;"

mkdir -p "$(dirname "$out")"
{
	echo "-- Schema of a database created by \`steno dev db migrate\` (Swift, GRDB)."
	echo "-- Generated by scripts/dump-swift-schema.sh; do not edit by hand."
	sqlite3 -batch -noheader "$tmp/steno.sqlite" "$query"
} | sed -e 's/[[:space:]]*$//' >"$out"

echo "wrote $out" >&2
