-- Schema of a database created by `steno dev db migrate` (Swift, GRDB).
-- Generated by scripts/dump-swift-schema.sh; do not edit by hand.
index|audioAsset_expiresAt|audioAsset|CREATE INDEX "audioAsset_expiresAt" ON "audioAsset"("expiresAt")
index|audioAsset_meetingID|audioAsset|CREATE INDEX "audioAsset_meetingID" ON "audioAsset"("meetingID")
index|decision_meetingID|decision|CREATE INDEX "decision_meetingID" ON "decision"("meetingID")
index|handoverReceipt_deviceID|handoverReceipt|CREATE INDEX "handoverReceipt_deviceID" ON "handoverReceipt"("deviceID")
index|meetingTask_meetingID|meetingTask|CREATE INDEX "meetingTask_meetingID" ON "meetingTask"("meetingID")
index|meeting_startedAt|meeting|CREATE INDEX "meeting_startedAt" ON "meeting"("startedAt")
index|meeting_state|meeting|CREATE INDEX "meeting_state" ON "meeting"("state")
index|participant_meetingID|participant|CREATE INDEX "participant_meetingID" ON "participant"("meetingID")
index|participant_personID|participant|CREATE INDEX "participant_personID" ON "participant"("personID")
index|speakerNameSuggestion_meetingID|speakerNameSuggestion|CREATE INDEX "speakerNameSuggestion_meetingID" ON "speakerNameSuggestion"("meetingID")
index|speaker_meetingID|speaker|CREATE INDEX "speaker_meetingID" ON "speaker"("meetingID")
index|speaker_personID|speaker|CREATE INDEX "speaker_personID" ON "speaker"("personID")
index|sqlite_autoindex_audioAsset_1|audioAsset|
index|sqlite_autoindex_decision_1|decision|
index|sqlite_autoindex_delivery_1|delivery|
index|sqlite_autoindex_delivery_2|delivery|
index|sqlite_autoindex_grdb_migrations_1|grdb_migrations|
index|sqlite_autoindex_handoverAdmission_1|handoverAdmission|
index|sqlite_autoindex_handoverReceipt_1|handoverReceipt|
index|sqlite_autoindex_meetingTask_1|meetingTask|
index|sqlite_autoindex_meeting_1|meeting|
index|sqlite_autoindex_pairedDevice_1|pairedDevice|
index|sqlite_autoindex_pairedDevice_2|pairedDevice|
index|sqlite_autoindex_participant_1|participant|
index|sqlite_autoindex_person_1|person|
index|sqlite_autoindex_setting_1|setting|
index|sqlite_autoindex_speakerNameSuggestion_1|speakerNameSuggestion|
index|sqlite_autoindex_speaker_1|speaker|
index|sqlite_autoindex_stageRate_1|stageRate|
index|sqlite_autoindex_transcriptSegment_1|transcriptSegment|
index|transcriptSegment_meetingID_start|transcriptSegment|CREATE INDEX "transcriptSegment_meetingID_start" ON "transcriptSegment"("meetingID", "start")
index|transcriptSegment_speakerID|transcriptSegment|CREATE INDEX "transcriptSegment_speakerID" ON "transcriptSegment"("speakerID")
table|audioAsset|audioAsset|CREATE TABLE "audioAsset" ("id" TEXT PRIMARY KEY NOT NULL, "meetingID" TEXT NOT NULL REFERENCES "meeting"("id") ON DELETE CASCADE, "url" TEXT NOT NULL, "format" TEXT NOT NULL, "lanes" TEXT NOT NULL, "sidecars16k" TEXT NOT NULL DEFAULT '{}', "mixdownURL" TEXT, "retention" TEXT NOT NULL, "retentionDays" INTEGER, "expiresAt" DATETIME)
table|decision|decision|CREATE TABLE "decision" ("id" TEXT PRIMARY KEY NOT NULL, "meetingID" TEXT NOT NULL REFERENCES "meeting"("id") ON DELETE CASCADE, "text" TEXT NOT NULL)
table|delivery|delivery|CREATE TABLE "delivery" ("id" TEXT PRIMARY KEY NOT NULL, "meetingID" TEXT NOT NULL REFERENCES "meeting"("id") ON DELETE CASCADE, "destinationID" TEXT NOT NULL, "status" TEXT NOT NULL, "failureMessage" TEXT, "lastAttemptAt" DATETIME, "receipt" TEXT, UNIQUE ("meetingID", "destinationID"))
table|grdb_migrations|grdb_migrations|CREATE TABLE grdb_migrations (identifier TEXT NOT NULL PRIMARY KEY)
table|handoverAdmission|handoverAdmission|CREATE TABLE "handoverAdmission" ("recordingID" TEXT NOT NULL, "byteCount" INTEGER NOT NULL, "sha256" BLOB NOT NULL, "meetingID" TEXT NOT NULL, "admittedAt" DATETIME NOT NULL, PRIMARY KEY ("recordingID", "byteCount", "sha256"))
table|handoverReceipt|handoverReceipt|CREATE TABLE "handoverReceipt" ("recordingID" TEXT PRIMARY KEY NOT NULL, "deviceID" TEXT NOT NULL REFERENCES "pairedDevice"("id") ON DELETE CASCADE, "state" TEXT NOT NULL, "meetingID" TEXT, "failureMessage" TEXT, "byteCount" INTEGER NOT NULL, "sha256" BLOB NOT NULL, "chunkSize" INTEGER NOT NULL, "receivedChunks" TEXT NOT NULL DEFAULT '[]', "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL)
table|meeting|meeting|CREATE TABLE "meeting" ("id" TEXT PRIMARY KEY NOT NULL, "title" TEXT NOT NULL, "startedAt" DATETIME NOT NULL, "duration" DOUBLE NOT NULL, "language" TEXT, "source" TEXT NOT NULL, "calendarEventID" TEXT, "tags" TEXT NOT NULL DEFAULT '[]', "state" TEXT NOT NULL, "failureReason" TEXT, "templateID" TEXT NOT NULL, "summary" TEXT, "summaryText" TEXT NOT NULL DEFAULT '', "scratchpad" TEXT NOT NULL DEFAULT '', "llmUsage" TEXT, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL, "endReason" TEXT, "titleOrigin" TEXT NOT NULL DEFAULT 'default')
table|meetingTask|meetingTask|CREATE TABLE "meetingTask" ("id" TEXT PRIMARY KEY NOT NULL, "meetingID" TEXT NOT NULL REFERENCES "meeting"("id") ON DELETE CASCADE, "text" TEXT NOT NULL, "assigneePersonID" TEXT REFERENCES "person"("id") ON DELETE SET NULL, "assigneeName" TEXT, "priority" TEXT NOT NULL, "dueDate" DATETIME, "done" BOOLEAN NOT NULL DEFAULT 0)
table|meeting_ft|meeting_ft|CREATE VIRTUAL TABLE "meeting_ft" USING fts5(title, summaryText, tokenize='''unicode61''', content='meeting')
table|meeting_ft_config|meeting_ft_config|CREATE TABLE 'meeting_ft_config'(k PRIMARY KEY, v) WITHOUT ROWID
table|meeting_ft_data|meeting_ft_data|CREATE TABLE 'meeting_ft_data'(id INTEGER PRIMARY KEY, block BLOB)
table|meeting_ft_docsize|meeting_ft_docsize|CREATE TABLE 'meeting_ft_docsize'(id INTEGER PRIMARY KEY, sz BLOB)
table|meeting_ft_idx|meeting_ft_idx|CREATE TABLE 'meeting_ft_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID
table|pairedDevice|pairedDevice|CREATE TABLE "pairedDevice" ("id" TEXT PRIMARY KEY NOT NULL, "name" TEXT NOT NULL, "pairedAt" DATETIME NOT NULL, "lastSeenAt" DATETIME, "tokenHash" BLOB NOT NULL UNIQUE)
table|participant|participant|CREATE TABLE "participant" ("id" TEXT PRIMARY KEY NOT NULL, "meetingID" TEXT NOT NULL REFERENCES "meeting"("id") ON DELETE CASCADE, "personID" TEXT REFERENCES "person"("id") ON DELETE SET NULL, "displayName" TEXT NOT NULL, "role" TEXT NOT NULL, "email" TEXT)
table|person|person|CREATE TABLE "person" ("id" TEXT PRIMARY KEY NOT NULL, "displayName" TEXT NOT NULL, "email" TEXT, "embedding" BLOB, "sampleCount" INTEGER NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL)
table|setting|setting|CREATE TABLE "setting" ("key" TEXT PRIMARY KEY NOT NULL, "value" TEXT NOT NULL)
table|speaker|speaker|CREATE TABLE "speaker" ("id" TEXT PRIMARY KEY NOT NULL, "meetingID" TEXT NOT NULL REFERENCES "meeting"("id") ON DELETE CASCADE, "clusterLabel" TEXT NOT NULL, "assignment" TEXT NOT NULL, "personID" TEXT REFERENCES "person"("id") ON DELETE SET NULL, "similarity" DOUBLE, "embedding" BLOB, "sampleClipStart" DOUBLE, "sampleClipEnd" DOUBLE, "sampleClipURL" TEXT, "clusterConfidence" DOUBLE NOT NULL)
table|speakerNameSuggestion|speakerNameSuggestion|CREATE TABLE "speakerNameSuggestion" ("speakerID" TEXT PRIMARY KEY NOT NULL REFERENCES "speaker"("id") ON DELETE CASCADE, "meetingID" TEXT NOT NULL REFERENCES "meeting"("id") ON DELETE CASCADE, "name" TEXT NOT NULL, "confidence" DOUBLE NOT NULL, "evidence" TEXT NOT NULL)
table|stageRate|stageRate|CREATE TABLE "stageRate" ("stage" TEXT NOT NULL, "key" TEXT NOT NULL, "samples" INTEGER NOT NULL, "secondsPerUnit" DOUBLE NOT NULL, "updatedAt" DATETIME NOT NULL, PRIMARY KEY ("stage", "key"))
table|transcriptSegment|transcriptSegment|CREATE TABLE "transcriptSegment" ("id" TEXT PRIMARY KEY NOT NULL, "meetingID" TEXT NOT NULL REFERENCES "meeting"("id") ON DELETE CASCADE, "start" DOUBLE NOT NULL, "end" DOUBLE NOT NULL, "speakerID" TEXT REFERENCES "speaker"("id") ON DELETE SET NULL, "lane" TEXT NOT NULL, "text" TEXT NOT NULL, "rawText" TEXT NOT NULL)
table|transcriptSegment_ft|transcriptSegment_ft|CREATE VIRTUAL TABLE "transcriptSegment_ft" USING fts5(text, tokenize='''unicode61''', content='transcriptSegment')
table|transcriptSegment_ft_config|transcriptSegment_ft_config|CREATE TABLE 'transcriptSegment_ft_config'(k PRIMARY KEY, v) WITHOUT ROWID
table|transcriptSegment_ft_data|transcriptSegment_ft_data|CREATE TABLE 'transcriptSegment_ft_data'(id INTEGER PRIMARY KEY, block BLOB)
table|transcriptSegment_ft_docsize|transcriptSegment_ft_docsize|CREATE TABLE 'transcriptSegment_ft_docsize'(id INTEGER PRIMARY KEY, sz BLOB)
table|transcriptSegment_ft_idx|transcriptSegment_ft_idx|CREATE TABLE 'transcriptSegment_ft_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID
trigger|__meeting_ft_ad|meeting|CREATE TRIGGER "__meeting_ft_ad" AFTER DELETE ON "meeting" BEGIN
    INSERT INTO "meeting_ft"("meeting_ft", "rowid", "title", "summaryText") VALUES('delete', old."rowid", old."title", old."summaryText");
END
trigger|__meeting_ft_ai|meeting|CREATE TRIGGER "__meeting_ft_ai" AFTER INSERT ON "meeting" BEGIN
    INSERT INTO "meeting_ft"("rowid", "title", "summaryText") VALUES (new."rowid", new."title", new."summaryText");
END
trigger|__meeting_ft_au|meeting|CREATE TRIGGER "__meeting_ft_au" AFTER UPDATE ON "meeting" BEGIN
    INSERT INTO "meeting_ft"("meeting_ft", "rowid", "title", "summaryText") VALUES('delete', old."rowid", old."title", old."summaryText");
    INSERT INTO "meeting_ft"("rowid", "title", "summaryText") VALUES (new."rowid", new."title", new."summaryText");
END
trigger|__transcriptSegment_ft_ad|transcriptSegment|CREATE TRIGGER "__transcriptSegment_ft_ad" AFTER DELETE ON "transcriptSegment" BEGIN
    INSERT INTO "transcriptSegment_ft"("transcriptSegment_ft", "rowid", "text") VALUES('delete', old."rowid", old."text");
END
trigger|__transcriptSegment_ft_ai|transcriptSegment|CREATE TRIGGER "__transcriptSegment_ft_ai" AFTER INSERT ON "transcriptSegment" BEGIN
    INSERT INTO "transcriptSegment_ft"("rowid", "text") VALUES (new."rowid", new."text");
END
trigger|__transcriptSegment_ft_au|transcriptSegment|CREATE TRIGGER "__transcriptSegment_ft_au" AFTER UPDATE ON "transcriptSegment" BEGIN
    INSERT INTO "transcriptSegment_ft"("transcriptSegment_ft", "rowid", "text") VALUES('delete', old."rowid", old."text");
    INSERT INTO "transcriptSegment_ft"("rowid", "text") VALUES (new."rowid", new."text");
END
migration|v1
migration|v2
migration|v3
migration|v4
migration|v5
